info:
  description: 微服务健康和日志监控
  version: 1.0.0
server:
  port: 7020
spring:
  application:
    name: mengcc-boot-admin
  security:
    user:
      password: 825116
      name: zhouzq
  cloud:
    nacos:
      discovery:
        server-addr: http://nacos.mengcc.cn/
management:
  endpoints:
    web:
      exposure:
        include: "*"
    endpoint:
      health:
        show-details: ALWAYS
  endpoint:
    logfile:
      external-file: /mengcc-cloud/logs/mengcc-boot-admin.log
logging:
  file: /mengcc-cloud/logs/mengcc-boot-admin.log
