server:
  port: 8768
spring:
  application:
    name: mengcc-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ZhouZhanQi/mengcc-config.git
          username: ZhouZhanQi
          password: jie116di825
          search-paths: ${doyd.yml.repo-dir}/{application}
management:
  endpoints:
    web:
      exposure:
        include: "*"
    endpoint:
      health:
        show-details: ALWAYS
  endpoint:
    logfile:
      external-file: /mengcc-cloud/logs/mengcc-config-server.log
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${eureka.instance.ip-address}:${server.port}
    health-check-url-path: /actuator/health
  client:
    # 客户端从Eureka Server集群里更新Eureka Server信息的频率
    eureka-service-url-poll-interval-seconds: 60
    # 定义从注册中心获取注册服务的信息
    registry-fetch-interval-seconds: 15
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
doyd:
  yml:
    repo-dir: /config-repo
    backup-dir: /config-backup
logging:
  file: doyd-config-server