info:
  description: 配置中心
  version: 1.0.0
server:
  port: 8768
spring:
  application:
    name: mengcc-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ZhouZhanQi/mengcc-config
          username: ZhouZhanQi
          password: 19931121@Zzq
          search-paths: ${mengcc.yml.repo-dir}/{application}
          skipSslValidation: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
    endpoint:
      health:
        show-details: ALWAYS
  endpoint:
    logfile:
      external-file: /mengcc-cloud/logs/mengcc-config-server.log
eureka:
  instance:
    prefer-ip-address: true
    ip-address: 172.24.174.30
    hostname: 172.24.174.30
    health-check-url-path: /actuator/health
  client:
    # 客户端从Eureka Server集群里更新Eureka Server信息的频率
    eureka-service-url-poll-interval-seconds: 60
    # 定义从注册中心获取注册服务的信息
    registry-fetch-interval-seconds: 15
    service-url:
      defaultZone: http://172.24.174.30:8761/eureka/
logging:
  file: /mengcc-cloud/logs/mengcc-config-server.log
mengcc:
  yml:
    repo-dir: /config-repo
    backup-dir: /config-backup