info:
  version: 1.0
  description: 后台用户中心
server:
  port: 9001
spring:
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      datasource:
        master:
          username: root
          password: 19931121@Zzq
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://47.108.78.70:3306/admin_user
  redis:
    host: 47.108.78.70
    port: 6379
    lettuce:
      pool:
        max-active: 10
        min-idle: 0
        max-idle: 10
        max-wait: 10000
mengcc:
  cache:
    type: redis
    enable: true
    clear-on-startup: true